Report soak test failures to sentry
[ci skip]

diff --git a/ci/pipeline.yaml b/ci/pipeline.yaml
--- a/ci/pipeline.yaml
+++ b/ci/pipeline.yaml
@@ -714,8 +714,19 @@ task_e2e_tests: &task_e2e_tests
         export GOPATH=$PWD/gopath
         cd gopath/src/github.com/sapcc/kubernikus
   
-        apk add --no-progress --no-cache make git
-        make test-e2e
+        apk add --no-progress --no-cache make git curl
+        make test-e2e | tee test.output
+        rc=$?
+        if [ "$SENTRY_DSN" != "" ] && [ $rc -ne 0 ] ; then
+          #Get the longest uniq (!) whitespace prefix of --- FAIL: lines
+          ws_count=$(grep -- '--- FAIL:' test.output| grep -v -- '->'| awk '{ match($0, /^ */); printf("%d\n", RLENGTH, substr($0,RLENGTH+1)) }' | sort|uniq -u |tail -1)
+          test_name=$(sed -n -E  "s/^ {$ws_count}--- FAIL: (.*) \([.0-9]*s\)$/\1/p" test.output)
+          curl -Lo sentry-cli -z sentry-cli https://github.com/getsentry/sentry-cli/releases/download/1.35.6/sentry-cli-Linux-x86_64
+          chmod +x sentry-cli
+          unset http_proxy https_proxy no_proxy
+          ./sentry-cli send-event -m "Failed to run $test_name" -E $OS_REGION_NAME --no-environ --logfile test.output
+        fi
+        exit $rc
   
   params:
     OS_AUTH_URL:
@@ -725,6 +736,7 @@ task_e2e_tests: &task_e2e_tests
     OS_PROJECT_NAME:
     OS_PROJECT_DOMAIN_NAME:
     OS_REGION_NAME:
+    SENTRY_DSN:
   
 
 task_build_args: &task_build_args
@@ -1308,6 +1320,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_ap-ae-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -1411,6 +1424,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_ap-au-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -1522,6 +1536,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_ap-cn-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -1633,6 +1648,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_ap-jp-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -1744,6 +1760,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_ap-jp-2
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -1855,6 +1872,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_ap-sa-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -1976,6 +1994,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_eu-de-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -2079,6 +2098,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_eu-de-2
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -2182,6 +2202,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_eu-nl-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -2293,6 +2314,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_eu-ru-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -2422,6 +2444,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_la-br-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -2533,6 +2556,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_na-ca-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -2636,6 +2660,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_na-us-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -2747,6 +2772,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_na-us-3
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
@@ -2876,6 +2902,7 @@ jobs:
         timeout: 45m
         params:
           <<: *auth_e2e_qa-de-1
+          SENTRY_DSN: ((sentry-soak-tests))
     <<: *slack
 
 
